openapi: 3.0.0
info:
  title: Raffle.ru
  description: "Публичное API"
  version: 1.0

servers:
  - url: http://raffle.local/api
    description: ""

################################################################################
paths:
  /raffle/view:
    get:
      summary: Получить конкурс
      description: Возвращает конкурс по уникальному коду
      tags:
        - Raffle
      parameters:
        - name: code
          in: query
          required: true
          description: Код конкурса
          schema:
            type: string
        - name: lang
          in: query
          required: false
          description: Error Language (en/ru)
          schema:
            type: string

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Raffle'
  /raffle/tags:
    get:
      summary: Получить тэги конкурса
      description: Вернет теги, которые закреплены к конкурсу по уникальному коду
      tags:
        - Raffle
      parameters:
        - name: code
          in: query
          required: true
          description: Код конкурса
          schema:
            type: string
        - name: lang
          in: query
          required: false
          description: Error Language (en/ru)
          schema:
            type: string

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
  /user/view:
    get:
      summary: Получить пользователя
      description: Возвращает пользователя по уникальному коду
      tags:
        - User
      parameters:
        - name: code
          in: query
          required: true
          description: Код пользователя
          schema:
            type: string

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /user/countsubscribers:
    get:
      summary: Количество подписчиков
      description: Возвращает количество подписчиков пользователя
      tags:
        - User
      parameters:
        - name: code
          in: query
          required: true
          description: Код пользователя
          schema:
            type: string

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: Количество подписчиков

  /user/countsubscriptions:
    get:
      summary: Количество подписок
      description: Возвращает количество подписок пользователя
      tags:
        - User
      parameters:
        - name: code
          in: query
          required: true
          description: Код пользователя
          schema:
            type: string

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: Количество подписок

  /user/subscribe:
    post:
      summary: Подписаться
      description: Подписывается на пользователя
      tags:
        - User
      parameters:
        - name: token
          in: path
          required: true
          description: токен текущего пользователя
          schema:
            type: string
        - name: user_code
          in: path
          required: true
          description: Код пользователя на которого подписываемся
          schema:
            type: string

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: boolean
                  description: Результат запроса
################################################################################
components:
  schemas:
    Raffle:
      properties:
        code:
          type: string
          description: Уникальный код конкурса
        title:
          type: string
          description: Заголовок конкурса
        short_description:
          type: string
          description: Короткое описание конкурса
        description:
          type: string
          description: Полное описание конкурса
        date_begin:
          type: string
          description: Дата начала конкурса
        date_end:
          type: string
          description: Дата окончания конкурса
        user_code:
          type: string
          description: User code author
    User:
      properties:
        code:
          type: string
          description: Уникальный код пользователя
        username:
          type: string
          description: Логин пользователя
        name:
          type: string
          description: Имя пользователя
        surname:
          type: string
          description: Фамилия пользователя
    Tag:
      properties:
        title:
          type: string
          description: Название тега